[Server]
host = 0.0.0.0
port = 3080
images_path = /data/imagenes
projects_path = /data/projects
appliances_path = /data/appliances
configs_path = /data/configs
symbols_path = /data/symbols
report_errors = True
auto_start = True
allow_console_from_anywhere = True
auth = False
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10000
udp_end_port_range = 20000
local = True
